[package]
name = "ml-rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
sdl2 = "0.35.2"
num_cpus = "1.13.1"
rayon = "1.5"
crossbeam = "0.8"
crossbeam-utils="0.8.8"
